# 线上配置文件
server:
  port: 8001
  servlet:
    session:
      cookie:
        # 解决跨域
        same-site: none
        secure: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # 指定 YAML 配置文件
    url: jdbc:shardingsphere:classpath:shardingsphere.yaml
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: admin
# AI 配置
ai:
  apiKey: 替换成自己的密钥